# fly.toml app configuration file generated for dungus on 2023-04-30T21:26:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dungus"
primary_region = "lax"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
